# -*- coding: utf-8 -*-
"""embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--aj4tKoIkMXKDJ1osP94brPd_dZWteR
"""

"""
=============================================================================
 IP5 핀테크 특허 패밀리 정제 파이프라인
 - 입력: merged_3files.csv (3기간 데이터가 이미 병합된 생 데이터)
 - 출력: fintech_patents_family_cleaned.csv
=============================================================================
핵심 원칙:
  1) 텍스트 대표 = 패밀리 내 Title+Abstract 길이가 가장 긴 문헌
     → NLP 품질 극대화 (영문 US/WO 문헌이 자동 선별됨)
  2) 출원 국가(Origin_Country) = 최초 우선권 주장 국가
     → "이 기술을 최초로 발명한 곳" 정보 보존
  3) 1 발명 = 1 문헌 (INPADOC Extended Family 기준)
     → 다국가 중복 출원으로 인한 통계적 왜곡 통제
=============================================================================
"""

import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 0. 설정
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INPUT_FILE = 'merged_3files.csv'
OUTPUT_FILE = 'fintech_patents_family_cleaned.csv'

# IP5 국가 코드
IP5_CODES = {'US', 'EP', 'CN', 'JP', 'KR'}

# 기간 구분 기준 (우선권 연도 기반으로 자동 부여)
PERIOD_BREAKS = {
    'Phase1_AI_Blockchain_2019_2021': (2019, 2021),
    'Phase2_LLM_Inflection_2022_2023': (2022, 2023),
    'Phase3_GenAI_OpenBanking_2024_2026': (2024, 2026),
}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 1. 데이터 로드 (CSV 파싱 오류 방어 포함)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def load_data(path):
    """
    CSV 로드 시 'EOF inside string' 등 파싱 오류 방어.
    - 1차: 기본 C 엔진으로 시도
    - 2차: Python 엔진 + on_bad_lines='skip'으로 재시도
    - 3차: 추가로 quoting=3(QUOTE_NONE)까지 적용
    """
    print(f"  로딩: {path}")

    # 1차 시도: 기본 C 엔진
    try:
        df = pd.read_csv(path, low_memory=False)
        print(f"  ✅ {len(df):,}건 로드됨 (C 엔진) | 컬럼 {len(df.columns)}개")
        return df
    except Exception as e:
        print(f"  ⚠️  C 엔진 실패: {e}")

    # 2차 시도: Python 엔진 + 불량 행 스킵
    try:
        df = pd.read_csv(path, low_memory=False, engine='python', on_bad_lines='skip')
        print(f"  ✅ {len(df):,}건 로드됨 (Python 엔진, bad lines skip) | 컬럼 {len(df.columns)}개")
        return df
    except Exception as e:
        print(f"  ⚠️  Python 엔진도 실패: {e}")

    # 3차 시도: 따옴표 무시 모드
    import csv
    try:
        df = pd.read_csv(
            path, low_memory=False, engine='python',
            on_bad_lines='skip', quoting=csv.QUOTE_NONE
        )
        print(f"  ✅ {len(df):,}건 로드됨 (QUOTE_NONE 모드) | 컬럼 {len(df.columns)}개")
        return df
    except Exception as e:
        raise RuntimeError(f"  ❌ CSV 로드 완전 실패: {e}")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 2. 기초 전처리
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def basic_preprocessing(df):

    # (A) Title [SEP] Abstract 결합
    df['Title'] = df['Title'].fillna('')
    df['Abstract'] = df['Abstract'].fillna('')
    df['_text'] = df['Title'].str.strip() + ' [SEP] ' + df['Abstract'].str.strip()
    df['_text_len'] = df['_text'].str.len()

    # (B) 날짜 변환
    for col in ['Earliest Priority Date', 'Application Date', 'Publication Date']:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')

    # (C) 피인용수 정수화
    df['Cited by Patent Count'] = pd.to_numeric(
        df['Cited by Patent Count'], errors='coerce'
    ).fillna(0).astype(int)

    # (D) 빈 텍스트 제거
    before = len(df)
    df = df[df['_text_len'] > 10].copy()
    if before > len(df):
        print(f"  텍스트 부족 행 제거: {before - len(df):,}건")

    # (E) IP5 필터
    if 'Jurisdiction' in df.columns:
        non_ip5 = (~df['Jurisdiction'].isin(IP5_CODES)).sum()
        if non_ip5 > 0:
            print(f"  비-IP5 관할 문헌 {non_ip5:,}건 제거")
            df = df[df['Jurisdiction'].isin(IP5_CODES)].copy()

    # (F) 기간 라벨 (출원일 Application Date 기준)
    df['_app_year'] = df['Application Date'].dt.year

    def assign_period(year):
        if pd.isna(year):
            return 'Unknown'
        y = int(year)
        for label, (s, e) in PERIOD_BREAKS.items():
            if s <= y <= e:
                return label
        return 'Unknown'

    df['Period'] = df['_app_year'].apply(assign_period)

    print(f"  기간별 분포:")
    for p, c in df['Period'].value_counts().sort_index().items():
        print(f"    {p}: {c:,}건")
    print(f"  ✅ 전처리 완료: {len(df):,}건")
    return df


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 3. 패밀리 ID 결정
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def assign_family_id(df):

    if 'Extended Family Members' in df.columns:
        def normalize_family(members_str):
            if pd.isna(members_str) or str(members_str).strip() == '':
                return None
            members = sorted(set(
                m.strip() for m in str(members_str).split(';;') if m.strip()
            ))
            return '||'.join(members) if members else None

        df['_family_key'] = df['Extended Family Members'].apply(normalize_family)
        no_family = df['_family_key'].isna()
        df.loc[no_family, '_family_key'] = df.loc[no_family, 'Lens ID']
        print(f"  Extended Family 기반 패밀리 ID 생성")
        print(f"  고유 패밀리 수: {df['_family_key'].nunique():,}")
    else:
        print("  [경고] Extended Family Members 없음 → Lens ID 사용")
        df['_family_key'] = df['Lens ID']

    return df


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 4. 최초 우선권 국가 추출
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def extract_priority_country(priority_numbers_str, jurisdiction_fallback):
    """
    Priority Numbers에서 최초 우선권 국가 코드 추출.
    예: 'US 202117546446 A;;KR 20190012345 A' → 'US'
    """
    if pd.isna(priority_numbers_str) or str(priority_numbers_str).strip() == '':
        return jurisdiction_fallback

    for p in str(priority_numbers_str).split(';;'):
        p = p.strip()
        if len(p) >= 2:
            country = p[:2].upper()
            if country in IP5_CODES:
                return country
    return jurisdiction_fallback


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 5. [핵심] 패밀리별 대표 선정 + 메타데이터 융합
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def process_family_group(group):

    # (1) 텍스트 대표: _text_len 최대
    rep = group.loc[group['_text_len'].idxmax()].copy()

    # (2) 최초 우선권 국가
    earliest_idx = group['Earliest Priority Date'].idxmin()
    earliest_row = group.loc[earliest_idx]
    origin = extract_priority_country(
        earliest_row.get('Priority Numbers', ''),
        earliest_row.get('Jurisdiction', 'UNKNOWN')
    )
    rep['Origin_Country'] = origin

    # (3) 패밀리 규모
    if 'Extended Family Size' in group.columns:
        rep['Final_Family_Size'] = group['Extended Family Size'].max()
    else:
        rep['Final_Family_Size'] = len(group)

    # (4) 진입 시장
    if 'Extended Family Member Jurisdictions' in group.columns:
        markets = set()
        for j in group['Extended Family Member Jurisdictions'].dropna():
            for code in str(j).split(';;'):
                c = code.strip()
                if c:
                    markets.add(c)
        rep['Target_Markets'] = ';;'.join(sorted(markets)) if markets else ''
        rep['Target_Market_Count'] = len(markets)
    else:
        jurs = set(group['Jurisdiction'].dropna().unique())
        rep['Target_Markets'] = ';;'.join(sorted(jurs))
        rep['Target_Market_Count'] = len(jurs)

    # (5) 패밀리 내 최대 피인용수
    rep['Family_Max_Cited'] = group['Cited by Patent Count'].max()

    # (6) 우선권 연도
    if pd.notna(earliest_row['Earliest Priority Date']):
        rep['Priority_Year'] = int(earliest_row['Earliest Priority Date'].year)
    else:
        rep['Priority_Year'] = rep.get('Publication Year', np.nan)

    return rep


def deduplicate_families(df):

    n_families = df['_family_key'].nunique()
    print(f"\n{'='*60}")
    print(f"  패밀리 정제 시작")
    print(f"  입력: {len(df):,}건 | 고유 패밀리: {n_families:,}개")
    print(f"{'='*60}")

    try:
        from tqdm import tqdm
        tqdm.pandas(desc="  패밀리 정제 중")
        result = df.groupby('_family_key').progress_apply(process_family_group)
    except ImportError:
        print("  (진행바 없이 처리 — 잠시 기다려주세요...)")
        result = df.groupby('_family_key').apply(process_family_group)

    result = result.reset_index(drop=True)
    print(f"\n  ✅ 패밀리 정제 완료")
    print(f"  출력: {len(result):,}건 (중복 제거: {len(df) - len(result):,}건)")
    return result


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 6. 최종 정리 및 저장
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def finalize_and_save(df, output_path):

    core_cols = [
        'Lens ID', '_family_key',
        'Title', 'Abstract', '_text', '_text_len',
        'Origin_Country', 'Jurisdiction', 'Priority_Year',
        'Publication Year', 'Period',
        'Cited by Patent Count', 'Family_Max_Cited', 'Cites Patent Count',
        'Final_Family_Size', 'Target_Markets', 'Target_Market_Count',
        'CPC Classifications', 'IPCR Classifications',
        'Applicants', 'Owners', 'Application Date',
        'Earliest Priority Date', 'Priority Numbers',
        'Legal Status', 'Display Key', 'URL',
    ]

    available = [c for c in core_cols if c in df.columns]
    df_final = df[available].copy()

    print(f"\n{'='*60}")
    print(f"  최종 데이터 요약")
    print(f"{'='*60}")
    print(f"  총 문헌 수: {len(df_final):,}")

    print(f"\n  ── 기간별 분포 ──")
    for p, c in df_final['Period'].value_counts().sort_index().items():
        print(f"    {p}: {c:,}건")

    print(f"\n  ── 국가별 분포 (Origin_Country) ──")
    for co, c in df_final['Origin_Country'].value_counts().head(10).items():
        print(f"    {co}: {c:,}건 ({c/len(df_final)*100:.1f}%)")

    tl = df_final['_text_len']
    print(f"\n  ── 텍스트 길이 ──")
    print(f"    평균: {tl.mean():.0f}자 | 중간값: {tl.median():.0f}자 | 최대: {tl.max():.0f}자")

    cited = df_final['Cited by Patent Count']
    print(f"\n  ── 피인용수 ──")
    print(f"    평균: {cited.mean():.1f} | 중간값: {cited.median():.0f} | 상위5%: {cited.quantile(0.95):.0f} | 최대: {cited.max():.0f}")

    df_final.to_csv(output_path, index=False, encoding='utf-8-sig')
    print(f"\n  ✅ 저장 완료: {output_path}")
    print(f"     파일 크기: {os.path.getsize(output_path) / (1024**2):.1f} MiB")
    return df_final


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 7. 메인
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def main():
    print("=" * 60)
    print("  IP5 핀테크 특허 패밀리 정제 파이프라인")
    print("  입력: merged_3files.csv")
    print("=" * 60)

    print("\n[Step 1] 데이터 로드")
    df = load_data(INPUT_FILE)

    print("\n[Step 2] 기초 전처리 + 기간 라벨")
    df = basic_preprocessing(df)

    print("\n[Step 3] 패밀리 ID 결정")
    df = assign_family_id(df)

    print("\n[Step 4] 패밀리 정제 (1 발명 = 1 문헌)")
    df_clean = deduplicate_families(df)

    print("\n[Step 5] 최종 저장")
    df_final = finalize_and_save(df_clean, OUTPUT_FILE)

    print(f"\n{'='*60}")
    print("  상위 5건 샘플")
    print("=" * 60)
    scols = ['Display Key', 'Origin_Country', 'Jurisdiction',
             'Priority_Year', 'Period', '_text_len',
             'Cited by Patent Count', 'Final_Family_Size']
    scols = [c for c in scols if c in df_final.columns]
    print(df_final[scols].head().to_string(index=False))

    return df_final


if __name__ == '__main__':
    df_result = main()

"""
=============================================================================
 IP5 핀테크 특허 패밀리 정제 파이프라인
 - 입력: merged_3files.csv (3기간 데이터가 이미 병합된 생 데이터)
 - 출력: fintech_patents_family_cleaned.csv
=============================================================================
핵심 원칙:
  1) 텍스트 대표 = 패밀리 내 Title+Abstract 길이가 가장 긴 문헌
     → NLP 품질 극대화 (영문 US/WO 문헌이 자동 선별됨)
  2) 출원 국가(Origin_Country) = 최초 우선권 주장 국가
     → "이 기술을 최초로 발명한 곳" 정보 보존
  3) 1 발명 = 1 문헌 (INPADOC Extended Family 기준)
     → 다국가 중복 출원으로 인한 통계적 왜곡 통제
=============================================================================
"""

import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 0. 설정
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INPUT_FILE = 'merged_3files.csv'
OUTPUT_FILE = 'fintech_patents_family_cleaned.csv'

# IP5 국가 코드
IP5_CODES = {'US', 'EP', 'CN', 'JP', 'KR'}

# 기간 구분 기준 (우선권 연도 기반으로 자동 부여)
PERIOD_BREAKS = {
    'Phase1_AI_Blockchain_2019_2021': (2019, 2021),
    'Phase2_LLM_Inflection_2022_2023': (2022, 2023),
    'Phase3_GenAI_OpenBanking_2024_2026': (2024, 2026),
}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 1. 데이터 로드
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def load_data(path):
    print(f"  로딩: {path}")
    df = pd.read_csv(path, low_memory=False, engine='python')
    print(f"  ✅ {len(df):,}건 로드됨 | 컬럼 {len(df.columns)}개")
    return df


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 2. 기초 전처리
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def basic_preprocessing(df):

    # (A) Title [SEP] Abstract 결합
    df['Title'] = df['Title'].fillna('')
    df['Abstract'] = df['Abstract'].fillna('')
    df['_text'] = df['Title'].str.strip() + ' [SEP] ' + df['Abstract'].str.strip()
    df['_text_len'] = df['_text'].str.len()

    # (B) 날짜 변환
    for col in ['Earliest Priority Date', 'Application Date', 'Publication Date']:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')

    # (C) 피인용수 정수화
    df['Cited by Patent Count'] = pd.to_numeric(
        df['Cited by Patent Count'], errors='coerce'
    ).fillna(0).astype(int)

    # (D) 빈 텍스트 제거
    before = len(df)
    df = df[df['_text_len'] > 10].copy()
    if before > len(df):
        print(f"  텍스트 부족 행 제거: {before - len(df):,}건")

    # (E) IP5 필터
    if 'Jurisdiction' in df.columns:
        non_ip5 = (~df['Jurisdiction'].isin(IP5_CODES)).sum()
        if non_ip5 > 0:
            print(f"  비-IP5 관할 문헌 {non_ip5:,}건 제거")
            df = df[df['Jurisdiction'].isin(IP5_CODES)].copy()

    # (F) 기간 라벨 (출원일 Application Date 기준)
    df['_app_year'] = df['Application Date'].dt.year

    def assign_period(year):
        if pd.isna(year):
            return 'Unknown'
        y = int(year)
        for label, (s, e) in PERIOD_BREAKS.items():
            if s <= y <= e:
                return label
        return 'Unknown'

    df['Period'] = df['_app_year'].apply(assign_period)

    print(f"  기간별 분포:")
    for p, c in df['Period'].value_counts().sort_index().items():
        print(f"    {p}: {c:,}건")
    print(f"  ✅ 전처리 완료: {len(df):,}건")
    return df


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 3. 패밀리 ID 결정
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def assign_family_id(df):

    if 'Extended Family Members' in df.columns:
        def normalize_family(members_str):
            if pd.isna(members_str) or str(members_str).strip() == '':
                return None
            members = sorted(set(
                m.strip() for m in str(members_str).split(';;') if m.strip()
            ))
            return '||'.join(members) if members else None

        df['_family_key'] = df['Extended Family Members'].apply(normalize_family)
        no_family = df['_family_key'].isna()
        df.loc[no_family, '_family_key'] = df.loc[no_family, 'Lens ID']
        print(f"  Extended Family 기반 패밀리 ID 생성")
        print(f"  고유 패밀리 수: {df['_family_key'].nunique():,}")
    else:
        print("  [경고] Extended Family Members 없음 → Lens ID 사용")
        df['_family_key'] = df['Lens ID']

    return df


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 4. 최초 우선권 국가 추출
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def extract_priority_country(priority_numbers_str, jurisdiction_fallback):
    """
    Priority Numbers에서 최초 우선권 국가 코드 추출.
    예: 'US 202117546446 A;;KR 20190012345 A' → 'US'
    """
    if pd.isna(priority_numbers_str) or str(priority_numbers_str).strip() == '':
        return jurisdiction_fallback

    for p in str(priority_numbers_str).split(';;'):
        p = p.strip()
        if len(p) >= 2:
            country = p[:2].upper()
            if country in IP5_CODES:
                return country
    return jurisdiction_fallback


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 5. [핵심] 패밀리별 대표 선정 + 메타데이터 융합
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def process_family_group(group):

    # (1) 텍스트 대표: _text_len 최대
    rep = group.loc[group['_text_len'].idxmax()].copy()

    # (2) 최초 우선권 국가
    earliest_idx = group['Earliest Priority Date'].idxmin()
    earliest_row = group.loc[earliest_idx]
    origin = extract_priority_country(
        earliest_row.get('Priority Numbers', ''),
        earliest_row.get('Jurisdiction', 'UNKNOWN')
    )
    rep['Origin_Country'] = origin

    # (3) 패밀리 규모
    if 'Extended Family Size' in group.columns:
        rep['Final_Family_Size'] = group['Extended Family Size'].max()
    else:
        rep['Final_Family_Size'] = len(group)

    # (4) 진입 시장
    if 'Extended Family Member Jurisdictions' in group.columns:
        markets = set()
        for j in group['Extended Family Member Jurisdictions'].dropna():
            for code in str(j).split(';;'):
                c = code.strip()
                if c:
                    markets.add(c)
        rep['Target_Markets'] = ';;'.join(sorted(markets)) if markets else ''
        rep['Target_Market_Count'] = len(markets)
    else:
        jurs = set(group['Jurisdiction'].dropna().unique())
        rep['Target_Markets'] = ';;'.join(sorted(jurs))
        rep['Target_Market_Count'] = len(jurs)

    # (5) 패밀리 내 최대 피인용수
    rep['Family_Max_Cited'] = group['Cited by Patent Count'].max()

    # (6) 우선권 연도
    if pd.notna(earliest_row['Earliest Priority Date']):
        rep['Priority_Year'] = int(earliest_row['Earliest Priority Date'].year)
    else:
        rep['Priority_Year'] = rep.get('Publication Year', np.nan)

    return rep


def deduplicate_families(df):

    n_families = df['_family_key'].nunique()
    print(f"\n{'='*60}")
    print(f"  패밀리 정제 시작")
    print(f"  입력: {len(df):,}건 | 고유 패밀리: {n_families:,}개")
    print(f"{'='*60}")

    try:
        from tqdm import tqdm
        tqdm.pandas(desc="  패밀리 정제 중")
        result = df.groupby('_family_key').progress_apply(process_family_group)
    except ImportError:
        print("  (진행바 없이 처리 — 잠시 기다려주세요...)")
        result = df.groupby('_family_key').apply(process_family_group)

    result = result.reset_index(drop=True)
    print(f"\n  ✅ 패밀리 정제 완료")
    print(f"  출력: {len(result):,}건 (중복 제거: {len(df) - len(result):,}건)")
    return result


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 6. 최종 정리 및 저장
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def finalize_and_save(df, output_path):

    core_cols = [
        'Lens ID', '_family_key',
        'Title', 'Abstract', '_text', '_text_len',
        'Origin_Country', 'Jurisdiction', 'Priority_Year',
        'Publication Year', 'Period',
        'Cited by Patent Count', 'Family_Max_Cited', 'Cites Patent Count',
        'Final_Family_Size', 'Target_Markets', 'Target_Market_Count',
        'CPC Classifications', 'IPCR Classifications',
        'Applicants', 'Owners', 'Application Date',
        'Earliest Priority Date', 'Priority Numbers',
        'Legal Status', 'Display Key', 'URL',
    ]

    available = [c for c in core_cols if c in df.columns]
    df_final = df[available].copy()

    print(f"\n{'='*60}")
    print(f"  최종 데이터 요약")
    print(f"{'='*60}")
    print(f"  총 문헌 수: {len(df_final):,}")

    print(f"\n  ── 기간별 분포 ──")
    for p, c in df_final['Period'].value_counts().sort_index().items():
        print(f"    {p}: {c:,}건")

    print(f"\n  ── 국가별 분포 (Origin_Country) ──")
    for co, c in df_final['Origin_Country'].value_counts().head(10).items():
        print(f"    {co}: {c:,}건 ({c/len(df_final)*100:.1f}%)")

    tl = df_final['_text_len']
    print(f"\n  ── 텍스트 길이 ──")
    print(f"    평균: {tl.mean():.0f}자 | 중간값: {tl.median():.0f}자 | 최대: {tl.max():.0f}자")

    cited = df_final['Cited by Patent Count']
    print(f"\n  ── 피인용수 ──")
    print(f"    평균: {cited.mean():.1f} | 중간값: {cited.median():.0f} | 상위5%: {cited.quantile(0.95):.0f} | 최대: {cited.max():.0f}")

    df_final.to_csv(output_path, index=False, encoding='utf-8-sig')
    print(f"\n  ✅ 저장 완료: {output_path}")
    print(f"     파일 크기: {os.path.getsize(output_path) / (1024**2):.1f} MiB")
    return df_final


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 7. 메인
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def main():
    print("=" * 60)
    print("  IP5 핀테크 특허 패밀리 정제 파이프라인")
    print("  입력: merged_3files.csv")
    print("=" * 60)

    print("\n[Step 1] 데이터 로드")
    df = load_data(INPUT_FILE)

    print("\n[Step 2] 기초 전처리 + 기간 라벨")
    df = basic_preprocessing(df)

    print("\n[Step 3] 패밀리 ID 결정")
    df = assign_family_id(df)

    print("\n[Step 4] 패밀리 정제 (1 발명 = 1 문헌)")
    df_clean = deduplicate_families(df)

    print("\n[Step 5] 최종 저장")
    df_final = finalize_and_save(df_clean, OUTPUT_FILE)

    print(f"\n{'='*60}")
    print("  상위 5건 샘플")
    print("=" * 60)
    scols = ['Display Key', 'Origin_Country', 'Jurisdiction',
             'Priority_Year', 'Period', '_text_len',
             'Cited by Patent Count', 'Final_Family_Size']
    scols = [c for c in scols if c in df_final.columns]
    print(df_final[scols].head().to_string(index=False))

    return df_final


if __name__ == '__main__':
    df_result = main()

"""
fintech_patents_family_cleaned.csv를 Period 컬럼 기준으로 3개 파일로 분리
"""

import pandas as pd

INPUT_FILE = 'fintech_patents_family_cleaned.csv'

df = pd.read_csv(INPUT_FILE, low_memory=False)
print(f"전체: {len(df):,}건\n")

for period, group in df.groupby('Period'):
    # 파일명: Period 라벨에서 간결한 이름 생성
    filename = f"family_cleaned_{period}.csv"
    group.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"  {period}: {len(group):,}건 → {filename}")

print("\n✅ 분리 완료")

"""
=============================================================================
 기간별 피인용 지수 계산 및 시드 특허 추출
 - 피인용 지수 = Cited by Patent Count ÷ 출원 후 경과연수
 - 각 기간별 상위 200개 → 총 600개 시드 특허
=============================================================================
"""

import pandas as pd
import numpy as np
from datetime import datetime

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 설정
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PERIOD_FILES = [
    'family_cleaned_Phase1_AI_Blockchain_2019_2021.csv',
    'family_cleaned_Phase2_LLM_Inflection_2022_2023.csv',
    'family_cleaned_Phase3_GenAI_OpenBanking_2024_2026.csv',
]

TOP_N = 200                      # 기간별 추출 수
REFERENCE_DATE = datetime(2026, 3, 1)  # 경과연수 계산 기준일
MIN_YEARS = 0.5                  # 최소 경과연수 (6개월) — 극단값 방지

OUTPUT_PER_PERIOD = True         # 기간별 파일도 저장할지
OUTPUT_MERGED = 'seed_patents_top600.csv'

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 처리
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

all_seeds = []

for filepath in PERIOD_FILES:
    print(f"\n{'='*60}")
    print(f"  처리: {filepath}")
    print(f"{'='*60}")

    df = pd.read_csv(filepath, low_memory=False)
    print(f"  로드: {len(df):,}건")

    # ── 출원일 파싱 ──
    df['Application Date'] = pd.to_datetime(df['Application Date'], errors='coerce')

    # ── 경과연수 계산 ──
    df['_years_elapsed'] = (REFERENCE_DATE - df['Application Date']).dt.days / 365.25
    # 출원일 없는 경우: Publication Year로 폴백
    missing_date = df['_years_elapsed'].isna()
    if missing_date.any() and 'Publication Year' in df.columns:
        df.loc[missing_date, '_years_elapsed'] = (
            REFERENCE_DATE.year - df.loc[missing_date, 'Publication Year']
        )
    # 최소값 클리핑 (출원 직후 특허가 피인용 지수 무한대 되는 것 방지)
    df['_years_elapsed'] = df['_years_elapsed'].clip(lower=MIN_YEARS)

    # ── 피인용수 정수화 ──
    df['Cited by Patent Count'] = pd.to_numeric(
        df['Cited by Patent Count'], errors='coerce'
    ).fillna(0)

    # ── 피인용 지수 = 피인용수 ÷ 경과연수 ──
    df['Citation_Index'] = df['Cited by Patent Count'] / df['_years_elapsed']
    df['Citation_Index'] = df['Citation_Index'].round(4)

    # ── 정렬 및 상위 추출 ──
    df_sorted = df.sort_values('Citation_Index', ascending=False)
    df_top = df_sorted.head(TOP_N).copy()
    df_top['Seed_Rank'] = range(1, len(df_top) + 1)

    # ── 통계 출력 ──
    ci = df['Citation_Index']
    ci_top = df_top['Citation_Index']
    print(f"\n  ── 전체 피인용 지수 분포 ──")
    print(f"    평균: {ci.mean():.3f} | 중간값: {ci.median():.3f} | 최대: {ci.max():.3f}")
    print(f"\n  ── 상위 {TOP_N}개 피인용 지수 ──")
    print(f"    최소: {ci_top.min():.3f} | 평균: {ci_top.mean():.3f} | 최대: {ci_top.max():.3f}")

    print(f"\n  ── 상위 {TOP_N}개 국가 분포 ──")
    if 'Origin_Country' in df_top.columns:
        for co, c in df_top['Origin_Country'].value_counts().items():
            print(f"    {co}: {c}건")

    # ── 기간별 파일 저장 ──
    if OUTPUT_PER_PERIOD:
        period_out = filepath.replace('family_cleaned_', 'seed_top200_')
        df_top.to_csv(period_out, index=False, encoding='utf-8-sig')
        print(f"\n  ✅ 저장: {period_out} ({len(df_top)}건)")

    all_seeds.append(df_top)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 통합 저장
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

df_all_seeds = pd.concat(all_seeds, ignore_index=True)
df_all_seeds.to_csv(OUTPUT_MERGED, index=False, encoding='utf-8-sig')

print(f"\n{'='*60}")
print(f"  최종 시드 특허 통합")
print(f"{'='*60}")
print(f"  총 시드 수: {len(df_all_seeds):,}건")
print(f"\n  ── 기간별 ──")
for p, c in df_all_seeds['Period'].value_counts().sort_index().items():
    print(f"    {p}: {c}건")
print(f"\n  ── 국가별 ──")
if 'Origin_Country' in df_all_seeds.columns:
    for co, c in df_all_seeds['Origin_Country'].value_counts().items():
        print(f"    {co}: {c}건 ({c/len(df_all_seeds)*100:.1f}%)")
print(f"\n  ✅ 저장 완료: {OUTPUT_MERGED}")

import csv

input_file = 'patent_classification_results.tsv'
output_file = 'patent_classification_results_clean.csv'

# 기대하는 컬럼의 개수 (헤더 기준 36개)
EXPECTED_COLS = 36

with open(input_file, 'r', encoding='utf-8') as infile, \
     open(output_file, 'w', encoding='utf-8-sig', newline='') as outfile:

    # quoting=csv.QUOTE_MINIMAL: 쉼표가 들어있는 문장들을 안전하게 큰따옴표로 감쌈
    writer = csv.writer(outfile, quoting=csv.QUOTE_MINIMAL)

    for i, line in enumerate(infile):
        line = line.rstrip('\n')
        # 우선 5칸 공백으로 전부 나눔 (초록/근거 때문에 50~80개로 쪼개짐)
        parts = line.split('     ')

        if len(parts) == EXPECTED_COLS:
            writer.writerow(parts)
            continue

        try:
            # 기준점 찾기: 역순으로 탐색하며 'confidence(high/medium/low)'와 'seed_quality(상/중/하)'를 찾음
            C = -1
            for j in range(len(parts) - 1, 0, -1):
                if parts[j] in ['high', 'medium', 'low', 'none', 'confidence'] and parts[j-1] in ['상', '중', '하', 'seed_quality']:
                    C = j
                    break

            if C != -1:
                # 1. 왼쪽 안전한 열 (Lens ID, _family_key, Title) 복원
                left_cols = parts[:3]
                title = parts[2]

                # 2. 오른쪽 안전한 열 (_text_len 부터 confidence 까지 30개 컬럼) 복원
                right_cols = parts[C-29 : C+1]

                # 3. reason 복원 (confidence 다음 위치부터 끝까지 다시 합침)
                reason = "     ".join(parts[C+1:])

                # 4. 중간에 끼어 쪼개진 Abstract와 _text 복원
                middle_str = "     ".join(parts[3 : C-29])

                # _text는 항상 "Title [SEP] Abstract" 구조이므로 이를 기준으로 앞뒤 분리
                sep_marker = f"{title} [SEP]"
                if sep_marker in middle_str:
                    split_idx = middle_str.find(sep_marker)
                    abstract = middle_str[:split_idx].strip()
                    _text = middle_str[split_idx:].strip()
                else:
                    abstract = middle_str
                    _text = middle_str

                # 36개 컬럼으로 완벽하게 조립 완료!
                final_row = left_cols + [abstract, _text] + right_cols + [reason]
                writer.writerow(final_row)
            else:
                # 패턴을 못 찾는 예외의 경우
                fallback_row = parts[:35] + ["     ".join(parts[35:])]
                writer.writerow(fallback_row)

        except Exception as e:
            print(f"Error on line {i}: {e}")
            writer.writerow(parts[:36])  # 에러 방지용

print(f"SUCCESS! '{output_file}' 생성 완료")

!pip install transformers torch pandas numpy scikit-learn tqdm

import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import os

# ==========================================
# 1. GPU 및 모델 초기화 (PaECTER)
# ==========================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"현재 사용 중인 장치: {device}")

model_name = "mpi-inno-comp/paecter"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name).to(device)
model.eval()

def get_embeddings(text_list, batch_size=32, desc="Embedding"):
    all_embeddings = []
    text_list = [str(t) if pd.notna(t) else "" for t in text_list]

    for i in tqdm(range(0, len(text_list), batch_size), desc=desc):
        batch_texts = text_list[i:i+batch_size]
        inputs = tokenizer(batch_texts, padding=True, truncation=True,
                           max_length=512, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)
            embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()
            all_embeddings.append(embeddings)
    return np.vstack(all_embeddings)

# ==========================================
# 2. 시드 특허 및 반례 특허 임베딩
# ==========================================
print("\n[1단계] 시드(진성) 및 반례(노이즈) 특허 임베딩 시작...")
seed_df = pd.read_csv('patent_classification_results_clean.csv')

seed_df['fintech_str'] = seed_df['fintech'].astype(str).str.strip().str.upper()
pos_seeds = seed_df[seed_df['fintech_str'] == 'TRUE'].copy()
neg_seeds = seed_df[(seed_df['fintech_str'] == 'FALSE') | (seed_df['fintech_str'] == 'OUT')].copy()

print(f"진성(Positive) 시드 개수: {len(pos_seeds)}개")
print(f"반례(Negative) 시드 개수: {len(neg_seeds)}개")

pos_vecs = get_embeddings(pos_seeds['_text'].tolist(), desc="Positive Seeds")
neg_vecs = get_embeddings(neg_seeds['_text'].tolist(), desc="Negative Seeds")

# ==========================================
# 3. 전체 패밀리 특허 데이터 임베딩
# ==========================================
print("\n[2단계] 전체 특허 데이터 임베딩 시작...")
full_df_path = 'fintech_patents_family_cleaned.csv'
full_df = pd.read_csv(full_df_path, low_memory=False)

if '_text' not in full_df.columns:
    full_df['_text'] = full_df['Title'].fillna('') + " [SEP] " + full_df['Abstract'].fillna('')

full_vecs = get_embeddings(full_df['_text'].tolist(), batch_size=64, desc="Full Dataset")

# ==========================================
# 4. Top-K Average 이진 분류 연산
# ==========================================
print("\n[3단계] Top-K 평균 기반 코사인 유사도 대결...")

# 비교할 상위 개수 (K값 설정)
K = 3  # 상위 3개의 점수 평균을 냅니다. (원하시면 5로 변경 가능)

# 전체 특허 vs 진성 시드 간의 모든 유사도 계산
sim_matrix_pos = cosine_similarity(full_vecs, pos_vecs)
# 전체 특허 vs 반례 시드 간의 모든 유사도 계산
sim_matrix_neg = cosine_similarity(full_vecs, neg_vecs)

# 진성 진영 Top-K 추출 및 평균 계산 (행별로 정렬 후 뒤에서 K개 추출)
top_k_pos_scores = np.sort(sim_matrix_pos, axis=1)[:, -K:]
full_df['top_k_pos_avg'] = top_k_pos_scores.mean(axis=1)

# 반례 진영 Top-K 추출 및 평균 계산
top_k_neg_scores = np.sort(sim_matrix_neg, axis=1)[:, -K:]
full_df['top_k_neg_avg'] = top_k_neg_scores.mean(axis=1)

# [판결] 긍정 진영 상위 3명의 평균 점수 > 부정 진영 상위 3명의 평균 점수
full_df['is_fintech'] = full_df['top_k_pos_avg'] > full_df['top_k_neg_avg']

# 결과 요약
true_fintech_count = full_df['is_fintech'].sum()
print(f"\n=== 분류 결과 (Top-{K} Average 방식) ===")
print(f"분석 대상 전체 특허 수: {len(full_df):,}개")
print(f"최종 핀테크 판별 특허 수: {true_fintech_count:,}개 ({(true_fintech_count/len(full_df))*100:.1f}%)")
print(f"노이즈/반례로 판별된 특허 수: {len(full_df) - true_fintech_count:,}개")

# 데이터 저장
output_path = 'final_fintech_patents_topK_filtered.csv'
fintech_final_df = full_df[full_df['is_fintech'] == True].copy()
fintech_final_df.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"\n최종 핀테크 특허 데이터가 저장되었습니다: {output_path}")

!pip install transformers torch pandas numpy scikit-learn tqdm

import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import os

# ==========================================
# 1. GPU 및 PaECTER 모델 초기화
# ==========================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"현재 사용 중인 장치: {device}")

model_name = "mpi-inno-comp/paecter"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name).to(device)
model.eval()

def get_embeddings(text_list, batch_size=32, desc="Embedding"):
    all_embeddings = []
    # 결측치(NaN) 안전 처리
    text_list = [str(t) if pd.notna(t) else "" for t in text_list]

    for i in tqdm(range(0, len(text_list), batch_size), desc=desc):
        batch_texts = text_list[i:i+batch_size]

        # 핵심!: 여기서 max_length=512와 truncation=True가
        # 512토큰을 넘어가는 긴 초록을 안전하게 자르고 처리합니다.
        inputs = tokenizer(batch_texts, padding=True, truncation=True,
                           max_length=512, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)
            # [CLS] 토큰 위치의 벡터 추출
            embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()
            all_embeddings.append(embeddings)

    return np.vstack(all_embeddings)

# ==========================================
# 2. 시드 특허 및 반례 특허 임베딩 (final_seed.csv)
# ==========================================
print("\n[1단계] 시드(진성) 및 반례(노이즈) 특허 데이터 로드 및 임베딩...")
# 사용자님이 알려주신 파일명으로 변경 완료
seed_df = pd.read_csv('final_seed.csv')

# fintech 컬럼(TRUE/FALSE) 기준으로 분리
seed_df['fintech_str'] = seed_df['fintech'].astype(str).str.strip().str.upper()
pos_seeds = seed_df[seed_df['fintech_str'] == 'TRUE'].copy()
neg_seeds = seed_df[(seed_df['fintech_str'] == 'FALSE') | (seed_df['fintech_str'] == 'OUT')].copy()

print(f"✔ 진성(Positive) 시드 개수: {len(pos_seeds)}개")
print(f"✔ 반례(Negative) 시드 개수: {len(neg_seeds)}개")

# _text 컬럼 사용 (이미 Title [SEP] Abstract 구조로 되어 있음)
pos_vecs = get_embeddings(pos_seeds['_text'].tolist(), desc="Positive Seeds")
neg_vecs = get_embeddings(neg_seeds['_text'].tolist(), desc="Negative Seeds")

# ==========================================
# 3. 전체 패밀리 데이터 임베딩 (fintech_patents_family_cleaned.csv)
# ==========================================
print("\n[2단계] 대규모 전체 특허 데이터 임베딩 시작...")
full_df = pd.read_csv('fintech_patents_family_cleaned.csv', low_memory=False)

# 만약 _text 컬럼이 누락된 데이터가 있다면 제목과 초록을 결합해주는 안전장치
if '_text' not in full_df.columns:
    full_df['_text'] = full_df['Title'].fillna('') + " [SEP] " + full_df['Abstract'].fillna('')

full_vecs = get_embeddings(full_df['_text'].tolist(), batch_size=64, desc="Full Dataset")

# ==========================================
# 4. Top-K Average 방식 코사인 유사도 경쟁
# ==========================================
print("\n[3단계] Top-K 평균 기반 이진 시멘틱 필터링...")
K = 3  # 상위 3개 비교

# 1) 코사인 유사도 행렬 계산
sim_matrix_pos = cosine_similarity(full_vecs, pos_vecs)
sim_matrix_neg = cosine_similarity(full_vecs, neg_vecs)

# 2) 진성 진영 Top-K 추출 및 평균 계산
top_k_pos_scores = np.sort(sim_matrix_pos, axis=1)[:, -K:]
full_df['top_k_pos_avg'] = top_k_pos_scores.mean(axis=1)

# 3) 반례 진영 Top-K 추출 및 평균 계산
top_k_neg_scores = np.sort(sim_matrix_neg, axis=1)[:, -K:]
full_df['top_k_neg_avg'] = top_k_neg_scores.mean(axis=1)

# 4) 최종 판결: 진성 진영 평균 점수가 더 높은가?
full_df['is_fintech'] = full_df['top_k_pos_avg'] > full_df['top_k_neg_avg']

# 결과 출력
true_fintech_count = full_df['is_fintech'].sum()
print(f"\n=== 최종 분류 결과 (Top-{K} Average) ===")
print(f"분석 대상 전체 특허 수: {len(full_df):,}건")
print(f"최종 핀테크 판별 특허 수: {true_fintech_count:,}건 ({(true_fintech_count/len(full_df))*100:.1f}%)")

# ==========================================
# 5. 최종 데이터 저장
# ==========================================
# 핀테크로 판별된(is_fintech == True) 데이터만 추출하여 저장
fintech_final_df = full_df[full_df['is_fintech'] == True].copy()
output_path = 'final_fintech_patents_filtered.csv'
fintech_final_df.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"\n✔ 최종 핀테크 특허 데이터셋 저장 완료: {output_path}")

import numpy as np
from google.colab import files

print("데이터 저장 및 다운로드를 준비합니다...")

# 1. 7만 건 전체 데이터 (진성 점수, 반례 점수, 판별 결과 포함) 저장
full_df.to_csv('full_patents_with_scores.csv', index=False, encoding='utf-8-sig')
print("✔ 전체 스코어 결과 CSV 저장 완료")

# 2. 임베딩 원본 벡터 데이터 (NPY 형식) 저장
np.save('pos_seeds_vectors.npy', pos_vecs)
np.save('neg_seeds_vectors.npy', neg_vecs)
np.save('full_patents_vectors.npy', full_vecs)
print("✔ 임베딩 벡터 데이터(NPY) 저장 완료")

# 3. 내 컴퓨터로 다운로드 실행
print("📥 브라우저를 통해 자동 다운로드를 시작합니다. (여러 개라 팝업 허용이 필요할 수 있습니다)")

# 원래 돌리시던 코드에서 만들어진 파일
files.download('final_fintech_patents_filtered.csv')
# 방금 새로 만든 파일 4개
files.download('full_patents_with_scores.csv')
files.download('pos_seeds_vectors.npy')
files.download('neg_seeds_vectors.npy')
files.download('full_patents_vectors.npy')

print("✨ 다운로드 요청이 완료되었습니다!")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA

# 한글 폰트 깨짐 방지 (Colab 환경)
import matplotlib.font_manager as fm
import os
os.system('apt-get install -y fonts-nanum')
fm.fontManager.addfont('/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf')
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

print("데이터를 불러오는 중입니다...")
# 1. 스코어 데이터 로드
df_scores = pd.read_csv('full_patents_with_scores.csv')

# ==========================================
# 📊 시각화 1: 이진 유사도 점수 대결 맵 (Score Competition)
# ==========================================
print("첫 번째 그래프(스코어 맵)를 그리는 중입니다...")
plt.figure(figsize=(10, 8))

# 전체 데이터가 너무 많으면 점이 뭉개지므로 1만 개만 샘플링하여 시각화 (패턴 확인용)
df_sample = df_scores.sample(n=min(10000, len(df_scores)), random_state=42)

# Scatter plot: x=반례 유사도, y=진성 유사도
sns.scatterplot(
    x='top_k_neg_avg',
    y='top_k_pos_avg',
    hue='is_fintech',
    palette={True: '#2ecc71', False: '#e74c3c'}, # 핀테크=초록, 노이즈=빨강
    data=df_sample,
    alpha=0.6,
    s=15,
    edgecolor=None
)

# 대각선 (결정 경계선: y = x)
min_val = min(df_sample['top_k_neg_avg'].min(), df_sample['top_k_pos_avg'].min())
max_val = max(df_sample['top_k_neg_avg'].max(), df_sample['top_k_pos_avg'].max())
plt.plot([min_val, max_val], [min_val, max_val], color='black', linestyle='--', linewidth=2, label='결정 경계 (y=x)')

plt.title('진성 시드 vs 반례 시드 유사도 대결 분포 (Top-K Average)', fontsize=16, pad=15)
plt.xlabel('반례(Negative) 시드와의 평균 유사도', fontsize=12)
plt.ylabel('진성(Positive) 시드와의 평균 유사도', fontsize=12)
plt.legend(title='최종 판별 (is_fintech)')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('score_competition_map.png', dpi=300)
plt.show()

# ==========================================
# 🌌 시각화 2: 2차원 시멘틱 은하수 맵 (t-SNE 차원 축소)
# ==========================================
print("\n두 번째 그래프(벡터 맵)를 준비 중입니다. 차원 축소 연산에 약 1~2분이 소요됩니다...")

# 2. 임베딩 원본 벡터 로드
pos_vecs = np.load('pos_seeds_vectors.npy')
neg_vecs = np.load('neg_seeds_vectors.npy')
full_vecs = np.load('full_patents_vectors.npy')

# 시각화를 위해 전체 특허 중 3,000개만 무작위 추출 (t-SNE는 연산이 매우 무겁습니다)
np.random.seed(42)
sample_indices = np.random.choice(full_vecs.shape[0], size=min(3000, full_vecs.shape[0]), replace=False)
full_vecs_sampled = full_vecs[sample_indices]
labels_sampled = df_scores['is_fintech'].iloc[sample_indices].values

# 시드 벡터와 섞어서 하나의 거대한 행렬로 만듦
all_vecs = np.vstack([pos_vecs, neg_vecs, full_vecs_sampled])

# 시각화를 위한 라벨 (0: 진성 시드, 1: 반례 시드, 2: 판별된 핀테크 특허, 3: 판별된 노이즈 특허)
labels = ['진성 시드 (Positive)'] * len(pos_vecs) + \
         ['반례 시드 (Negative)'] * len(neg_vecs) + \
         ['분류됨: 핀테크 (True)'] * sum(labels_sampled == True) + \
         ['분류됨: 노이즈 (False)'] * sum(labels_sampled == False)

# 순서 맞추기 위해 배열 분리 계산
is_fintech_mask = labels_sampled == True
full_fintech_vecs = full_vecs_sampled[is_fintech_mask]
full_noise_vecs = full_vecs_sampled[~is_fintech_mask]

# 다시 순서대로 결합
all_vecs_ordered = np.vstack([pos_vecs, neg_vecs, full_fintech_vecs, full_noise_vecs])

# PCA로 50차원으로 먼저 줄인 뒤, t-SNE로 2차원으로 축소 (정확도와 속도를 위한 정석 기법)
pca = PCA(n_components=50, random_state=42)
vecs_pca = pca.fit_transform(all_vecs_ordered)

tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
vecs_2d = tsne.fit_transform(vecs_pca)

# 결과를 데이터프레임으로
df_tsne = pd.DataFrame(vecs_2d, columns=['X', 'Y'])
df_tsne['Label'] = labels

# 그래프 그리기
plt.figure(figsize=(12, 10))

# 1) 판별된 일반 특허들 먼저 흐리게 찍기 (배경)
sns.scatterplot(data=df_tsne[df_tsne['Label'].str.contains('분류됨')], x='X', y='Y', hue='Label',
                palette={'분류됨: 핀테크 (True)': '#a8e6cf', '분류됨: 노이즈 (False)': '#fab1a0'},
                alpha=0.4, s=20, edgecolor=None)

# 2) 시드 특허(거점)들을 크고 진하게 그 위에 찍기
sns.scatterplot(data=df_tsne[df_tsne['Label'].str.contains('시드')], x='X', y='Y', hue='Label',
                palette={'진성 시드 (Positive)': '#27ae60', '반례 시드 (Negative)': '#c0392b'},
                alpha=1.0, s=150, edgecolor='black', marker='X')

plt.title('핀테크 특허 시멘틱 벡터 공간 (t-SNE 2D Projection)', fontsize=18, pad=15)
plt.legend(title='특허 그룹', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig('semantic_tsne_map.png', dpi=300)
plt.show()

print("\n✨ 시각화 완료! 두 개의 그래프 이미지 파일(.png)이 저장되었습니다.")

import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA

print("3차원 시각화를 위한 데이터를 준비하고 축소 연산을 시작합니다 (약 2~3분 소요)...")

# 1. 스코어 데이터 및 임베딩 벡터 로드
df_scores = pd.read_csv('full_patents_with_scores.csv')
pos_vecs = np.load('pos_seeds_vectors.npy')
neg_vecs = np.load('neg_seeds_vectors.npy')
full_vecs = np.load('full_patents_vectors.npy')

# 2. 연산 속도와 시각적 명확성을 위해 전체 특허 중 3,000개만 샘플링
np.random.seed(42)
sample_indices = np.random.choice(full_vecs.shape[0], size=min(3000, full_vecs.shape[0]), replace=False)
full_vecs_sampled = full_vecs[sample_indices]
labels_sampled = df_scores['is_fintech'].iloc[sample_indices].values

# 3. 데이터 결합 (시드 + 샘플링된 일반 특허)
is_fintech_mask = labels_sampled == True
full_fintech_vecs = full_vecs_sampled[is_fintech_mask]
full_noise_vecs = full_vecs_sampled[~is_fintech_mask]

all_vecs_ordered = np.vstack([pos_vecs, neg_vecs, full_fintech_vecs, full_noise_vecs])

# 4. 라벨 및 마커 크기 설정
labels = ['진성 핀테크 시드'] * len(pos_vecs) + \
         ['비핀테크 반례 시드'] * len(neg_vecs) + \
         ['판별됨: 핀테크'] * len(full_fintech_vecs) + \
         ['판별됨: 노이즈'] * len(full_noise_vecs)

# 시드는 크게(10), 일반 특허는 작게(3) 보이도록 설정
sizes = [10] * (len(pos_vecs) + len(neg_vecs)) + [3] * (len(full_fintech_vecs) + len(full_noise_vecs))

# 5. 차원 축소: 1024D -> PCA(50D) -> t-SNE(3D)
pca = PCA(n_components=50, random_state=42)
vecs_pca = pca.fit_transform(all_vecs_ordered)

tsne_3d = TSNE(n_components=3, random_state=42, perplexity=30, n_iter=1000)
vecs_3d = tsne_3d.fit_transform(vecs_pca)

# 6. Plotly용 DataFrame 생성
df_3d = pd.DataFrame(vecs_3d, columns=['X', 'Y', 'Z'])
df_3d['Label'] = labels
df_3d['Size'] = sizes

# 7. Interactive 3D Scatter Plot 그리기
fig = px.scatter_3d(
    df_3d,
    x='X', y='Y', z='Z',
    color='Label',
    size='Size',
    size_max=15, # 최대 크기 제한
    opacity=0.7,
    color_discrete_map={
        '진성 핀테크 시드': '#27ae60', # 진한 초록
        '비핀테크 반례 시드': '#c0392b', # 진한 빨강
        '판별됨: 핀테크': '#a8e6cf',     # 연한 초록
        '판별됨: 노이즈': '#fab1a0'      # 연한 빨강
    },
    title="핀테크 특허 시멘틱 벡터 공간 (Interactive 3D t-SNE)"
)

# 배경색 어둡게 설정 (은하수 느낌)
fig.update_layout(
    scene=dict(
        xaxis=dict(backgroundcolor="black", gridcolor="gray", showbackground=True, zerolinecolor="white"),
        yaxis=dict(backgroundcolor="black", gridcolor="gray", showbackground=True, zerolinecolor="white"),
        zaxis=dict(backgroundcolor="black", gridcolor="gray", showbackground=True, zerolinecolor="white"),
    ),
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    legend_title_text='특허 그룹 분류'
)

print("✨ 마우스로 드래그해서 3차원 공간을 돌려보세요!")
fig.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
import plotly.express as px

# [Colab 한글 폰트 설정]
import matplotlib.font_manager as fm
import os
os.system('apt-get install -y fonts-nanum')
fm.fontManager.addfont('/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf')
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

print("저장된 벡터 데이터를 불러오고 있습니다...")
full_df = pd.read_csv('full_patents_with_scores.csv')
pos_vecs = np.load('pos_seeds_vectors.npy')
neg_vecs = np.load('neg_seeds_vectors.npy')
full_vecs = np.load('full_patents_vectors.npy')

# 코사인 유사도 행렬 계산 (한 번만 계산해두면 K를 계속 바꿔가며 쓸 수 있습니다)
print("전체 특허와 시드 간의 코사인 유사도를 계산 중입니다...")
sim_matrix_pos = cosine_similarity(full_vecs, pos_vecs)
sim_matrix_neg = cosine_similarity(full_vecs, neg_vecs)

# ==========================================
# 1. K=1, 3, 5, 7, 9 민감도 분석 및 Jaccard 유사도 계산
# ==========================================
k_values = [1, 3, 5, 7, 9]
results_dict = {}

print("\n💡 [K값 변화에 따른 핀테크 판별 결과]")
for k in k_values:
    # 각 K값에 대한 Top-K 평균 계산
    pos_avg = np.sort(sim_matrix_pos, axis=1)[:, -k:].mean(axis=1)
    neg_avg = np.sort(sim_matrix_neg, axis=1)[:, -k:].mean(axis=1)

    # 판별 결과 저장 (True/False)
    is_fintech = pos_avg > neg_avg
    results_dict[k] = is_fintech
    print(f" - K={k} 일 때 핀테크 판별 건수: {is_fintech.sum():,}건")

# Jaccard 유사도 행렬 계산 함수 (교집합 / 합집합)
def jaccard_similarity(list1, list2):
    intersection = np.logical_and(list1, list2).sum()
    union = np.logical_or(list1, list2).sum()
    return intersection / union if union != 0 else 0

jaccard_matrix = np.zeros((len(k_values), len(k_values)))
for i, k1 in enumerate(k_values):
    for j, k2 in enumerate(k_values):
        jaccard_matrix[i, j] = jaccard_similarity(results_dict[k1], results_dict[k2])

# 기준값(K=3)과 다른 K값들의 평균 일치율(Robustness) 확인
k3_comparisons = [jaccard_similarity(results_dict[3], results_dict[k]) for k in k_values if k != 3]
mean_jaccard_k3 = np.mean(k3_comparisons)
print(f"\n🔥 [논문 기재용 핵심 수치] K=3 기준, 타 K값들과의 평균 자카드 유사도: {mean_jaccard_k3*100:.2f}%")

# ==========================================
# 2. 민감도 분석 시각화 (Jaccard Heatmap)
# ==========================================
plt.figure(figsize=(7, 5))
sns.heatmap(jaccard_matrix, annot=True, fmt=".3f", cmap="YlGnBu",
            xticklabels=[f"K={k}" for k in k_values],
            yticklabels=[f"K={k}" for k in k_values], vmin=0.8, vmax=1.0)
plt.title("K값 변화에 따른 판별 결과 자카드 유사도 (Jaccard Similarity)", fontsize=14, pad=15)
plt.tight_layout()
plt.savefig('jaccard_sensitivity_heatmap.png', dpi=300)
plt.show()

# ==========================================
# 3. 강건성(Robustness) 증명용 2D & 3D t-SNE 시각화 준비
# ==========================================
print("\n🌌 2차원/3차원 시각화를 위한 차원 축소를 시작합니다 (약 2~3분 소요)...")

# 각 특허가 5번의 테스트(K=1,3,5,7,9) 중 몇 번이나 '핀테크'로 판별되었는지 합산 (0 ~ 5)
robustness_score = sum(results_dict[k] for k in k_values)

# 시각화를 위해 3000개 샘플링
np.random.seed(42)
sample_indices = np.random.choice(full_vecs.shape[0], size=min(3000, full_vecs.shape[0]), replace=False)
full_vecs_sampled = full_vecs[sample_indices]
robust_sampled = robustness_score[sample_indices]

# 시드 벡터와 병합
all_vecs = np.vstack([pos_vecs, neg_vecs, full_vecs_sampled])

# 강건성에 따른 라벨링 (논문 디펜스 핵심)
labels = ['1. 진성 시드 (Pos)'] * len(pos_vecs) + \
         ['2. 반례 시드 (Neg)'] * len(neg_vecs)

for score in robust_sampled:
    if score == 5:
        labels.append('3. 강건한 핀테크 (5/5 일치)')
    elif score == 0:
        labels.append('5. 강건한 노이즈 (0/5 일치)')
    else:
        labels.append(f'4. 경계선/변동 (일치율 변동)') # 1~4번 일치한 회색지대

# 1024D -> 50D(PCA) -> 2D/3D(t-SNE) 압축
pca = PCA(n_components=50, random_state=42)
vecs_pca = pca.fit_transform(all_vecs)

# 2D t-SNE
tsne_2d = TSNE(n_components=2, random_state=42, perplexity=30)
vecs_2d = tsne_2d.fit_transform(vecs_pca)

# 3D t-SNE
tsne_3d = TSNE(n_components=3, random_state=42, perplexity=30)
vecs_3d = tsne_3d.fit_transform(vecs_pca)

# ==========================================
# 4. 2차원 (2D) 강건성 시각화
# ==========================================
df_2d = pd.DataFrame(vecs_2d, columns=['X', 'Y'])
df_2d['Label'] = labels

# 마커 크기: 시드는 크게, 나머지는 작게
sizes = [150 if '시드' in label else 20 for label in labels]
markers = ['X' if '시드' in label else 'o' for label in labels]

plt.figure(figsize=(12, 9))
palette_2d = {
    '1. 진성 시드 (Pos)': '#27ae60',
    '2. 반례 시드 (Neg)': '#c0392b',
    '3. 강건한 핀테크 (5/5 일치)': '#a8e6cf',
    '4. 경계선/변동 (일치율 변동)': '#f39c12', # 주황색 (회색지대)
    '5. 강건한 노이즈 (0/5 일치)': '#fab1a0'
}

sns.scatterplot(data=df_2d.sort_values('Label'), x='X', y='Y', hue='Label',
                palette=palette_2d, style='Label', markers={'1. 진성 시드 (Pos)':'X', '2. 반례 시드 (Neg)':'X',
                '3. 강건한 핀테크 (5/5 일치)':'o', '4. 경계선/변동 (일치율 변동)':'o', '5. 강건한 노이즈 (0/5 일치)':'o'},
                alpha=0.7, edgecolor=None)

plt.title('K-NN 민감도 강건성(Robustness) 2D 시각화', fontsize=16, pad=15)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig('robustness_2d_tsne.png', dpi=300)
plt.show()

# ==========================================
# 5. 3차원 (3D) 강건성 인터랙티브 시각화 (Plotly)
# ==========================================
df_3d = pd.DataFrame(vecs_3d, columns=['X', 'Y', 'Z'])
df_3d['Label'] = labels
df_3d['Size'] = [8 if '시드' in label else 3 for label in labels]

fig = px.scatter_3d(
    df_3d.sort_values('Label'), x='X', y='Y', z='Z',
    color='Label', size='Size', size_max=10, opacity=0.7,
    color_discrete_map=palette_2d,
    title="K-NN 민감도 강건성(Robustness) 3D 공간 시각화"
)

fig.update_layout(
    scene=dict(
        xaxis=dict(backgroundcolor="black", gridcolor="gray"),
        yaxis=dict(backgroundcolor="black", gridcolor="gray"),
        zaxis=dict(backgroundcolor="black", gridcolor="gray"),
    ),
    paper_bgcolor="black", plot_bgcolor="black", font=dict(color="white"),
    legend_title_text='분류 강건성'
)
print("✨ 마우스로 3차원 공간을 돌려가며 확인해보세요!")
fig.show()

# UMAP 라이브러리 설치 (코랩에 기본 설치되어 있지 않으므로 필수!)
!pip install umap-learn plotly

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import umap

# [Colab 한글 폰트 설정]
import matplotlib.font_manager as fm
import os
os.system('apt-get install -y fonts-nanum')
fm.fontManager.addfont('/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf')
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

print("데이터를 불러오고 있습니다...")
# 기존 점수와 벡터 로드
df = pd.read_csv('full_patents_with_scores.csv')
pos_vecs = np.load('pos_seeds_vectors.npy')
neg_vecs = np.load('neg_seeds_vectors.npy')
full_vecs = np.load('full_patents_vectors.npy')

# K=3 판별 결과 사용 (full_patents_with_scores.csv의 기본값이 K=3이었습니다)
# 명확하게 하기 위해 K=3 기준으로 다시 boolean 마스크 생성
is_fintech_k3 = df['is_fintech'].values

# ==========================================
# 1. 시각화용 데이터 샘플링 및 병합
# ==========================================
print("시각화를 위해 3000개의 특허를 샘플링하고 라벨을 부여합니다...")
np.random.seed(42)
# 전체 데이터 7만개를 다 찍으면 점이 겹쳐서 안 보이므로 3000개만 무작위 추출
sample_indices = np.random.choice(full_vecs.shape[0], size=min(3000, full_vecs.shape[0]), replace=False)
full_vecs_sampled = full_vecs[sample_indices]
labels_sampled = is_fintech_k3[sample_indices]

# 진성 시드, 반례 시드, 샘플링된 일반 특허 병합
all_vecs = np.vstack([pos_vecs, neg_vecs, full_vecs_sampled])

# 라벨링 설정 (논문 그래프용)
labels = ['1. 진성 시드 거점 (Positive)'] * len(pos_vecs) + \
         ['2. 반례 시드 거점 (Negative)'] * len(neg_vecs) + \
         ['3. 판별됨: 핀테크 특허 (K=3)'] * sum(labels_sampled == True) + \
         ['4. 판별됨: 노이즈 특허 (K=3)'] * sum(labels_sampled == False)

# 다시 순서대로 쪼개기 위한 준비 (색상을 예쁘게 칠하기 위해)
fintech_mask = labels_sampled == True
full_fintech_vecs = full_vecs_sampled[fintech_mask]
full_noise_vecs = full_vecs_sampled[~fintech_mask]

# 최종 순서: 진성시드 -> 반례시드 -> 합격특허 -> 탈락특허
all_vecs_ordered = np.vstack([pos_vecs, neg_vecs, full_fintech_vecs, full_noise_vecs])

# ==========================================
# 2. UMAP 차원 축소 (Metric='cosine' 핵심!)
# ==========================================
print("\n🚀 UMAP 알고리즘을 통해 768차원 우주를 축소합니다 (t-SNE보다 훨씬 빠릅니다!)...")

# PCA를 거칠 필요 없이 UMAP은 고차원을 바로 축소하는 데 탁월합니다.
# metric='cosine'을 적용하여 우리가 필터링할 때 쓴 코사인 유사도를 그대로 보존합니다!

# 2D UMAP
reducer_2d = umap.UMAP(n_components=2, metric='cosine', random_state=42, n_neighbors=15, min_dist=0.1)
vecs_2d = reducer_2d.fit_transform(all_vecs_ordered)

# 3D UMAP
reducer_3d = umap.UMAP(n_components=3, metric='cosine', random_state=42, n_neighbors=15, min_dist=0.1)
vecs_3d = reducer_3d.fit_transform(all_vecs_ordered)

# ==========================================
# 3. UMAP 2차원 (2D) 시각화 (정적인 논문 삽입용)
# ==========================================
df_2d = pd.DataFrame(vecs_2d, columns=['UMAP_1', 'UMAP_2'])
df_2d['Label'] = labels

# 팔레트 및 마커 설정
palette = {
    '1. 진성 시드 거점 (Positive)': '#27ae60', # 진초록
    '2. 반례 시드 거점 (Negative)': '#c0392b', # 진빨강
    '3. 판별됨: 핀테크 특허 (K=3)': '#a8e6cf', # 연초록
    '4. 판별됨: 노이즈 특허 (K=3)': '#fab1a0'  # 연분홍
}

plt.figure(figsize=(12, 9))
sns.scatterplot(data=df_2d.sort_values('Label'), x='UMAP_1', y='UMAP_2', hue='Label',
                palette=palette, style='Label',
                markers={'1. 진성 시드 거점 (Positive)':'X', '2. 반례 시드 거점 (Negative)':'X',
                         '3. 판별됨: 핀테크 특허 (K=3)':'o', '4. 판별됨: 노이즈 특허 (K=3)':'o'},
                alpha=0.6, s=30, edgecolor=None)

# 시드를 눈에 띄게 한 번 더 덧그리기 (강조)
seed_df = df_2d[df_2d['Label'].str.contains('시드')]
sns.scatterplot(data=seed_df, x='UMAP_1', y='UMAP_2', hue='Label', palette=palette,
                style='Label', markers={'1. 진성 시드 거점 (Positive)':'X', '2. 반례 시드 거점 (Negative)':'X'},
                s=150, edgecolor='black', legend=False)

plt.title('UMAP 기반 핀테크 특허 시멘틱 지형도 (2D, metric=cosine)', fontsize=16, pad=15)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig('umap_2d_landscape.png', dpi=300)
plt.show()

# ==========================================
# 4. UMAP 3차원 (3D) 인터랙티브 시각화
# ==========================================
df_3d = pd.DataFrame(vecs_3d, columns=['UMAP_1', 'UMAP_2', 'UMAP_3'])
df_3d['Label'] = labels
df_3d['Size'] = [8 if '시드' in label else 3 for label in labels]

fig = px.scatter_3d(
    df_3d.sort_values('Label'), x='UMAP_1', y='UMAP_2', z='UMAP_3',
    color='Label', size='Size', size_max=12, opacity=0.7,
    color_discrete_map=palette,
    title="UMAP 기반 핀테크 특허 시멘틱 지형도 (3D Interactive)"
)

fig.update_layout(
    scene=dict(
        xaxis=dict(backgroundcolor="black", gridcolor="gray"),
        yaxis=dict(backgroundcolor="black", gridcolor="gray"),
        zaxis=dict(backgroundcolor="black", gridcolor="gray"),
    ),
    paper_bgcolor="black", plot_bgcolor="black", font=dict(color="white"),
    legend_title_text='분류 그룹'
)
print("\n✨ UMAP 3D 시각화 완료! 마우스로 우주 공간을 돌려보세요.")
fig.show()

