# -*- coding: utf-8 -*-
"""임베딩성능평가.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFznRGib-9Ec3DTe2173RK0foFyDv99p
"""

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 1: 데이터 로드 및 본문 핵심 수치 사전 검증
# ─────────────────────────────────────────────────────────────

# 1) 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 2) 경로 지정
import pandas as pd
import os

BASE_PATH = '/content/drive/MyDrive/논문'
SCORES_PATH = os.path.join(BASE_PATH, 'full_patents_with_scores.csv')
SEED_PATH = os.path.join(BASE_PATH, 'final_seed.csv')

# 3) 파일 존재 확인
print("[파일 경로 확인]")
for p in [SCORES_PATH, SEED_PATH]:
    print(f"  {'✓' if os.path.exists(p) else '✗'} {p}")

# 4) 데이터 로드
df_scores = pd.read_csv(SCORES_PATH, low_memory=False)
df_seed = pd.read_csv(SEED_PATH, low_memory=False)

print(f"\n[full_patents_with_scores.csv]")
print(f"  행 수:    {len(df_scores):,}")
print(f"  컬럼 수:  {df_scores.shape[1]}")
required_cols_scores = {'top_k_pos_avg', 'top_k_neg_avg', 'is_fintech', '_family_key'}
print(f"  주요 컬럼 모두 존재: {required_cols_scores.issubset(df_scores.columns)}")

print(f"\n[final_seed.csv]")
print(f"  행 수:    {len(df_seed):,}")
print(f"  컬럼 수:  {df_seed.shape[1]}")
required_cols_seed = {'fintech', '_family_key'}
print(f"  주요 컬럼 모두 존재: {required_cols_seed.issubset(df_seed.columns)}")

# 5) 본문 핵심 수치 사전 검증
print("\n" + "=" * 55)
print(" 본문 핵심 수치 검증")
print("=" * 55)

# 5-1) is_fintech 컬럼 dtype 방어 처리 (bool 또는 문자열 모두 대응)
def count_true_false(series):
    if series.dtype == bool:
        return int(series.sum()), int((~series).sum())
    s = series.astype(str).str.strip().str.upper()
    return int((s == 'TRUE').sum()), int((s == 'FALSE').sum())

true_count, false_count = count_true_false(df_scores['is_fintech'])
total = len(df_scores)

print(f"\n[71,663건 모집단 기반 분류 결과]")
print(f"  진성   (is_fintech = True):  {true_count:,}건  ({true_count/total*100:.1f}%)")
print(f"  노이즈 (is_fintech = False): {false_count:,}건  ({false_count/total*100:.1f}%)")
print(f"  합계: {total:,}건")
match_pop = (true_count == 21381 and false_count == 50282)
print(f"  → 본문 인용값(21,381 / 50,282)과 일치: {'✓' if match_pop else '✗'}")

# 5-2) 시드 라벨 카운트
seed_true, seed_false = count_true_false(df_seed['fintech'])
print(f"\n[final_seed.csv 라벨 카운트]")
print(f"  시드     (fintech = TRUE):  {seed_true}건")
print(f"  안티시드 (fintech = FALSE): {seed_false}건")
print(f"  합계: {len(df_seed)}건")
match_seed = (seed_true == 157 and seed_false == 443)
print(f"  → 3.4절 본문(157 / 443)과 일치: {'✓' if match_seed else '✗'}")

print("\n[결론]")
if match_pop and match_seed:
    print("  모든 핵심 수치가 본문과 일치합니다. 다음 셀(Cohen's d)로 진행 가능.")
else:
    print("  ※ 불일치 항목이 있습니다. 다음 셀로 진행하기 전에 원인 확인 필요.")

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 2: Cohen's d 산출
# ─────────────────────────────────────────────────────────────

import numpy as np
from scipy import stats

# 1) net_score 컬럼 생성
df_scores['net_score'] = df_scores['top_k_pos_avg'] - df_scores['top_k_neg_avg']

# 2) 그룹 분리 (dtype 방어 처리)
if df_scores['is_fintech'].dtype == bool:
    mask_true = df_scores['is_fintech']
else:
    mask_true = df_scores['is_fintech'].astype(str).str.strip().str.upper() == 'TRUE'

net_true  = df_scores.loc[mask_true,  'net_score'].values
net_false = df_scores.loc[~mask_true, 'net_score'].values
n1, n2 = len(net_true), len(net_false)

# 3) 기술통계량 출력
def describe(arr, name):
    return {
        'name': name, 'n': len(arr),
        'mean': float(np.mean(arr)),
        'sd':   float(np.std(arr, ddof=1)),
        'median': float(np.median(arr)),
        'q1': float(np.percentile(arr, 25)),
        'q3': float(np.percentile(arr, 75)),
        'min': float(np.min(arr)), 'max': float(np.max(arr)),
    }

stat_true  = describe(net_true,  'True (진성)')
stat_false = describe(net_false, 'False (노이즈)')

print("=" * 60)
print(" net_score (= top_k_pos_avg - top_k_neg_avg) 기술통계량")
print("=" * 60)
for s in [stat_true, stat_false]:
    print(f"\n[{s['name']}] n = {s['n']:,}")
    print(f"  평균   (Mean):    {s['mean']:+.6f}")
    print(f"  표준편차(SD):     {s['sd']:.6f}")
    print(f"  중앙값 (Median):  {s['median']:+.6f}")
    print(f"  Q1 / Q3:          {s['q1']:+.6f} / {s['q3']:+.6f}")
    print(f"  최소 / 최대:      {s['min']:+.6f} / {s['max']:+.6f}")

# 4) Cohen's d 산출
m1, m2 = stat_true['mean'], stat_false['mean']
sd1, sd2 = stat_true['sd'], stat_false['sd']
pooled_sd = np.sqrt(((n1 - 1) * sd1**2 + (n2 - 1) * sd2**2) / (n1 + n2 - 2))
cohens_d = (m1 - m2) / pooled_sd

# 5) Hedges' g (작은 표본 보정 — 표본이 크면 d와 거의 동일)
correction = 1 - (3 / (4 * (n1 + n2) - 9))
hedges_g = cohens_d * correction

# 6) Cohen's d 95% 신뢰구간 (정규근사)
se_d = np.sqrt((n1 + n2) / (n1 * n2) + cohens_d**2 / (2 * (n1 + n2)))
ci_lower = cohens_d - 1.96 * se_d
ci_upper = cohens_d + 1.96 * se_d

# 7) 해석 라벨 (Cohen 1988 기준)
def interpret_d(d):
    a = abs(d)
    if a < 0.2:  return "negligible (무시할 수준)"
    if a < 0.5:  return "small (작은 효과)"
    if a < 0.8:  return "medium (중간 효과)"
    return "large (큰 효과)"

# 8) Welch's t-test 재산출 (본문 인용값 검증)
t_stat, p_val = stats.ttest_ind(net_true, net_false, equal_var=False)

# 9) 결과 출력
print("\n" + "=" * 60)
print(" 효과 크기 산출 결과")
print("=" * 60)

print(f"\n[Cohen's d]")
print(f"  d = {cohens_d:.4f}")
print(f"  95% CI: [{ci_lower:.4f}, {ci_upper:.4f}]")
print(f"  해석: {interpret_d(cohens_d)}")

print(f"\n[Hedges' g (작은 표본 보정)]")
print(f"  g = {hedges_g:.4f}   (보정계수 {correction:.6f})")

print(f"\n[Welch's t-test 재산출 — 본문 인용값 검증]")
print(f"  t = {t_stat:.2f}      (본문 인용: 315.12)")
print(f"  p = {p_val:.3e}       (본문 인용: < 0.001)")

print(f"\n[본문 인용 평균값 검증]")
print(f"  진성 평균:   {m1:+.5f}   (본문 인용: +0.00213)")
print(f"  노이즈 평균: {m2:+.5f}   (본문 인용: -0.00478)")

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 3: Precision-Recall 자기참조 검증
# ─────────────────────────────────────────────────────────────

from sklearn.metrics import (
    confusion_matrix, precision_score, recall_score,
    f1_score, accuracy_score
)

# 1) ground truth / prediction 정규화 (bool, 문자열 모두 대응)
def to_bool(series):
    if series.dtype == bool:
        return series.astype(bool)
    return series.astype(str).str.strip().str.upper() == 'TRUE'

df_seed['_gt']    = to_bool(df_seed['fintech'])      # ground truth
df_scores['_pred'] = to_bool(df_scores['is_fintech']) # prediction

# 2) _family_key 기준 매칭
merged = df_seed[['_family_key', '_gt']].merge(
    df_scores[['_family_key', '_pred']],
    on='_family_key',
    how='left'
)

# 3) 매칭 진단 출력
total_seed = len(df_seed)
matched   = int(merged['_pred'].notna().sum())
unmatched = int(merged['_pred'].isna().sum())

print("=" * 60)
print(" 시드 600건의 모집단(71,663건) 매칭 진단")
print("=" * 60)
print(f"  시드 총 건수: {total_seed}건")
print(f"  매칭 성공:    {matched}건  ({matched/total_seed*100:.1f}%)")
print(f"  매칭 실패:    {unmatched}건  ({unmatched/total_seed*100:.1f}%)")

if unmatched > 0:
    print(f"\n  ※ 매칭 실패한 시드의 라벨 분포:")
    unmatched_seeds = merged[merged['_pred'].isna()]
    for label in [True, False]:
        cnt = int((unmatched_seeds['_gt'] == label).sum())
        print(f"    fintech = {label}: {cnt}건")

# 4) 매칭 성공분만으로 지표 산출
matched_df = merged[merged['_pred'].notna()].copy()
y_true = matched_df['_gt'].astype(bool).values
y_pred = matched_df['_pred'].astype(bool).values

# 5) 혼동행렬 (양성 = True)
cm = confusion_matrix(y_true, y_pred, labels=[False, True])
tn, fp, fn, tp = cm.ravel()

print("\n" + "=" * 60)
print(" 자기참조 검증 결과 (양성 = TRUE 진성 핀테크)")
print("=" * 60)

print(f"\n[혼동행렬]")
print(f"                          예측 FALSE   예측 TRUE")
print(f"  실제 FALSE (안티시드)   {tn:>8}     {fp:>8}")
print(f"  실제 TRUE  (시드)       {fn:>8}     {tp:>8}")

# 6) 성능 지표
precision = precision_score(y_true, y_pred, pos_label=True, zero_division=0)
recall    = recall_score(y_true, y_pred, pos_label=True, zero_division=0)
f1        = f1_score(y_true, y_pred, pos_label=True, zero_division=0)
accuracy  = accuracy_score(y_true, y_pred)
specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

print(f"\n[성능 지표]")
print(f"  Precision   = TP / (TP+FP)   = {precision:.4f}   ({tp} / {tp+fp})")
print(f"  Recall      = TP / (TP+FN)   = {recall:.4f}   ({tp} / {tp+fn})")
print(f"  F1 Score                     = {f1:.4f}")
print(f"  Accuracy    = (TP+TN)/Total  = {accuracy:.4f}   ({tp+tn} / {len(y_true)})")
print(f"  Specificity = TN / (TN+FP)   = {specificity:.4f}   ({tn} / {tn+fp})")

print(f"\n[직관적 해석]")
print(f"  - 분류기가 '시드'라고 부른 것 중 {precision*100:.1f}%가 실제 시드")
print(f"  - 실제 시드 중 {recall*100:.1f}%를 분류기가 올바르게 식별")
print(f"  - 실제 안티시드 중 {specificity*100:.1f}%를 분류기가 올바르게 거부")

# 다음 셀(B-1 / 셀 4)에서 저장에 사용할 변수 보관
_results_b1 = {
    'cohens_d': cohens_d,
    'ci_lower': ci_lower,
    'ci_upper': ci_upper,
    'hedges_g': hedges_g,
    't_stat': t_stat,
    'p_val': p_val,
    'mean_true': m1,
    'mean_false': m2,
    'sd_true': sd1,
    'sd_false': sd2,
    'n_true': n1,
    'n_false': n2,
    'matched': matched,
    'unmatched': unmatched,
    'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn),
    'precision': precision, 'recall': recall, 'f1': f1,
    'accuracy': accuracy, 'specificity': specificity,
}
print("\n[변수 보관 완료] 다음 셀(셀 4)에서 통합 CSV로 저장합니다.")

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 4: 통합 결과 CSV 저장 (부록 <표 A-2> 자료)
# ─────────────────────────────────────────────────────────────

import pandas as pd
from datetime import datetime

r = _results_b1

# 메타데이터
metadata = [
    {'Category': '메타', 'Metric': '산출 일자', 'Value': datetime.now().strftime('%Y-%m-%d'), 'Detail': ''},
    {'Category': '메타', 'Metric': '모집단 크기', 'Value': '71,663건', 'Detail': 'INPADOC 패밀리 정제 후'},
    {'Category': '메타', 'Metric': '진성 (is_fintech=True)', 'Value': '21,381건', 'Detail': '29.8%'},
    {'Category': '메타', 'Metric': '노이즈 (is_fintech=False)', 'Value': '50,282건', 'Detail': '70.2%'},
    {'Category': '메타', 'Metric': '시드 (fintech=TRUE)',     'Value': '157건', 'Detail': 'final_seed.csv'},
    {'Category': '메타', 'Metric': '안티시드 (fintech=FALSE)', 'Value': '443건', 'Detail': 'final_seed.csv'},
]

# 본문 지표
rows = [
    {'Category': '분포 비교',     'Metric': '진성 그룹 평균 (net_score)',
     'Value': f"{r['mean_true']:+.6f}",  'Detail': f"n={r['n_true']:,}, SD={r['sd_true']:.6f}"},
    {'Category': '분포 비교',     'Metric': '노이즈 그룹 평균 (net_score)',
     'Value': f"{r['mean_false']:+.6f}", 'Detail': f"n={r['n_false']:,}, SD={r['sd_false']:.6f}"},
    {'Category': '분포 비교',     'Metric': "Welch's t 통계량",
     'Value': f"{r['t_stat']:.2f}",      'Detail': "p < 0.001"},
    {'Category': '효과 크기',     'Metric': "Cohen's d",
     'Value': f"{r['cohens_d']:.4f}",
     'Detail': f"95% CI [{r['ci_lower']:.4f}, {r['ci_upper']:.4f}], 'large' (Cohen 1988)"},
    {'Category': '효과 크기',     'Metric': "Hedges' g (소표본 보정)",
     'Value': f"{r['hedges_g']:.4f}",    'Detail': "보정계수 ≈ 1.0 (대표본)"},
    {'Category': '자기참조 검증', 'Metric': '매칭 성공 / 총 시드',
     'Value': f"{r['matched']} / {r['matched']+r['unmatched']}",
     'Detail': "_family_key 매칭, 100%"},
    {'Category': '자기참조 검증', 'Metric': '혼동행렬 (TP / FP / FN / TN)',
     'Value': f"{r['tp']} / {r['fp']} / {r['fn']} / {r['tn']}",
     'Detail': "양성 = TRUE 진성 핀테크"},
    {'Category': '자기참조 검증', 'Metric': 'Precision',
     'Value': f"{r['precision']:.4f}", 'Detail': f"{r['tp']} / ({r['tp']}+{r['fp']})"},
    {'Category': '자기참조 검증', 'Metric': 'Recall',
     'Value': f"{r['recall']:.4f}",    'Detail': f"{r['tp']} / ({r['tp']}+{r['fn']})"},
    {'Category': '자기참조 검증', 'Metric': 'F1 Score',
     'Value': f"{r['f1']:.4f}",        'Detail': "Precision·Recall 조화평균"},
    {'Category': '자기참조 검증', 'Metric': 'Accuracy',
     'Value': f"{r['accuracy']:.4f}",  'Detail': f"({r['tp']}+{r['tn']}) / 600"},
    {'Category': '자기참조 검증', 'Metric': 'Specificity',
     'Value': f"{r['specificity']:.4f}", 'Detail': f"{r['tn']} / ({r['tn']}+{r['fp']})"},
]

df_final = pd.DataFrame(metadata + rows)

# 저장
output_path = os.path.join(BASE_PATH, 'Semantic_Validation_Metrics.csv')
df_final.to_csv(output_path, index=False, encoding='utf-8-sig')

print("=" * 60)
print(" 통합 결과 저장 완료")
print("=" * 60)
print(f"\n  저장 경로: {output_path}")
print(f"  행 수:    {len(df_final)}")

print(f"\n[부록 <표 A-2> 미리보기]")
print(df_final.to_string(index=False))

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 5: 임베딩 벡터 로드 + 시드/안티시드 인덱스 매핑
# ─────────────────────────────────────────────────────────────

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# 1) 벡터 파일 로드
VECTORS_PATH = os.path.join(BASE_PATH, 'full_patents_vectors.npy')
print(f"[벡터 파일 로드] {VECTORS_PATH}")
full_vecs = np.load(VECTORS_PATH)
print(f"  shape: {full_vecs.shape}")
print(f"  dtype: {full_vecs.dtype}")

# 2) 모집단 행 수와 벡터 수 일치 확인
assert full_vecs.shape[0] == len(df_scores), \
    f"벡터 수({full_vecs.shape[0]})와 모집단 행 수({len(df_scores)})가 불일치"
print(f"  ✓ 벡터 수와 모집단 행 수 일치: {full_vecs.shape[0]:,}건")

# 3) df_scores의 인덱스 리셋 (안전장치)
df_scores = df_scores.reset_index(drop=True)

# 4) _family_key → 모집단 row index 매핑 딕셔너리 생성
key_to_idx = pd.Series(
    df_scores.index.values,
    index=df_scores['_family_key']
).to_dict()

# 5) 시드 600건의 모집단 인덱스 매핑
df_seed_indexed = df_seed.copy()
df_seed_indexed['_pop_idx'] = df_seed_indexed['_family_key'].map(key_to_idx)
df_seed_indexed['_gt'] = to_bool(df_seed_indexed['fintech'])

matched_n   = int((~df_seed_indexed['_pop_idx'].isna()).sum())
unmatched_n = int(df_seed_indexed['_pop_idx'].isna().sum())

print(f"\n[시드 600건의 모집단 인덱스 매핑]")
print(f"  매칭 성공: {matched_n}건")
print(f"  매칭 실패: {unmatched_n}건")
if unmatched_n > 0:
    print(f"  ※ 매칭 실패한 시드의 라벨 분포:")
    miss = df_seed_indexed[df_seed_indexed['_pop_idx'].isna()]
    for label in [True, False]:
        cnt = int((miss['_gt'] == label).sum())
        print(f"    fintech = {label}: {cnt}건")

# 6) 시드/안티시드 분리 및 모집단 인덱스 추출
df_valid = df_seed_indexed.dropna(subset=['_pop_idx']).copy()
df_valid['_pop_idx'] = df_valid['_pop_idx'].astype(int)

pos_pop_indices = df_valid[df_valid['_gt'] == True ]['_pop_idx'].values
neg_pop_indices = df_valid[df_valid['_gt'] == False]['_pop_idx'].values

print(f"\n[시드/안티시드 분리]")
print(f"  시드 (fintech=True):    {len(pos_pop_indices)}건  (예상 157)")
print(f"  안티시드 (fintech=False): {len(neg_pop_indices)}건  (예상 443)")

# 7) 모집단 벡터에서 시드/안티시드 벡터 직접 슬라이싱
pos_vecs = full_vecs[pos_pop_indices]
neg_vecs = full_vecs[neg_pop_indices]
print(f"\n[추출된 시드/안티시드 벡터]")
print(f"  pos_vecs shape: {pos_vecs.shape}   (예상 (157, 1024))")
print(f"  neg_vecs shape: {neg_vecs.shape}   (예상 (443, 1024))")

# 8) Sanity check: 자기 자신과의 코사인 유사도 = 1.0 확인
sample_n = 5
sample_idx = pos_pop_indices[:sample_n]
sample_vec = full_vecs[sample_idx]
self_sims = np.diag(cosine_similarity(sample_vec, sample_vec))

print(f"\n[Sanity check: 시드 상위 {sample_n}건의 자기-유사도]")
for i, (idx, sim) in enumerate(zip(sample_idx, self_sims)):
    flag = "✓" if abs(sim - 1.0) < 1e-5 else "✗"
    print(f"  {flag} 시드 {i+1} (모집단 인덱스 {idx}): cos_sim(self, self) = {sim:.6f}")

all_self_match = np.allclose(self_sims, 1.0, atol=1e-5)

print(f"\n[셀 5 요약]")
print(f"  모집단 벡터:    shape {full_vecs.shape}")
print(f"  시드 인덱스:    {len(pos_pop_indices)}개 (모집단 내 위치)")
print(f"  안티시드 인덱스: {len(neg_pop_indices)}개 (모집단 내 위치)")
print(f"  매핑 정합성:    {'✓ 정상' if all_self_match else '✗ 자기-유사도 1.0 불일치 — 매핑 점검 필요'}")
print(f"  → 다음 셀(셀 6)에서 LOO Top-3 평균 재계산 가능")

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 6: Leave-One-Out 재산출 + LOO Precision-Recall
# ─────────────────────────────────────────────────────────────

K = 3  # K-NN의 K값 (embedding.py와 동일)

# ── Step 1) 유사도 행렬 4종 계산 ──────────────────────────
# 시드 i 평가용
sim_pos_for_pos = cosine_similarity(pos_vecs, pos_vecs)  # (157, 157) — 자기 자신 마스킹 대상
sim_neg_for_pos = cosine_similarity(pos_vecs, neg_vecs)  # (157, 443) — 자기 자신 없음

# 안티시드 j 평가용
sim_pos_for_neg = cosine_similarity(neg_vecs, pos_vecs)  # (443, 157) — 자기 자신 없음
sim_neg_for_neg = cosine_similarity(neg_vecs, neg_vecs)  # (443, 443) — 자기 자신 마스킹 대상

# ── Step 2) 자기-유사도 마스킹 (-inf로 치환하여 Top-3에서 제외) ──
np.fill_diagonal(sim_pos_for_pos, -np.inf)
np.fill_diagonal(sim_neg_for_neg, -np.inf)

# ── Step 3) Top-K 평균 산출 (시드 영역) ────────────────────
top_k_pos_for_pos = np.sort(sim_pos_for_pos, axis=1)[:, -K:].mean(axis=1)  # 시드의 시드 방향
top_k_neg_for_pos = np.sort(sim_neg_for_pos, axis=1)[:, -K:].mean(axis=1)  # 시드의 안티시드 방향

# ── Step 4) Top-K 평균 산출 (안티시드 영역) ────────────────
top_k_pos_for_neg = np.sort(sim_pos_for_neg, axis=1)[:, -K:].mean(axis=1)
top_k_neg_for_neg = np.sort(sim_neg_for_neg, axis=1)[:, -K:].mean(axis=1)

# ── Step 5) 시드 600건 통합 결과 만들기 ────────────────────
loo_df = pd.DataFrame({
    '_pop_idx':       np.concatenate([pos_pop_indices, neg_pop_indices]),
    '_gt':            np.concatenate([np.ones(len(pos_pop_indices), dtype=bool),
                                       np.zeros(len(neg_pop_indices), dtype=bool)]),
    'top_k_pos_LOO':  np.concatenate([top_k_pos_for_pos, top_k_pos_for_neg]),
    'top_k_neg_LOO':  np.concatenate([top_k_neg_for_pos, top_k_neg_for_neg]),
})
loo_df['net_score_LOO'] = loo_df['top_k_pos_LOO'] - loo_df['top_k_neg_LOO']
loo_df['pred_LOO']      = loo_df['top_k_pos_LOO'] > loo_df['top_k_neg_LOO']

# 원본(자기참조 포함) 예측을 동일 인덱스 기준으로 가져오기
loo_df = loo_df.merge(
    df_scores[['_family_key']].reset_index().rename(columns={'index': '_pop_idx'}),
    on='_pop_idx', how='left'
)
loo_df['pred_orig'] = df_scores.loc[loo_df['_pop_idx'], 'is_fintech'].values
loo_df['pred_orig'] = loo_df['pred_orig'].astype(bool)

# ── Step 6) 원본 vs LOO 예측 변동 진단 ─────────────────────
flipped = (loo_df['pred_orig'] != loo_df['pred_LOO']).sum()

print("=" * 60)
print(" 원본(자기참조 포함) vs LOO(자기참조 제거) 예측 비교")
print("=" * 60)
print(f"  총 시드 600건 중 예측이 뒤집힌 건수: {flipped}건")
if flipped > 0:
    print(f"\n  ※ 뒤집힌 시드의 라벨 분포:")
    flipped_df = loo_df[loo_df['pred_orig'] != loo_df['pred_LOO']]
    for label, name in [(True, '시드'), (False, '안티시드')]:
        cnt = (flipped_df['_gt'] == label).sum()
        print(f"    실제 {name} (fintech={label}): {cnt}건")

# ── Step 7) LOO 기준 Precision-Recall 산출 ─────────────────
y_true_loo = loo_df['_gt'].values
y_pred_loo = loo_df['pred_LOO'].values

cm_loo = confusion_matrix(y_true_loo, y_pred_loo, labels=[False, True])
tn_l, fp_l, fn_l, tp_l = cm_loo.ravel()

precision_loo   = precision_score(y_true_loo, y_pred_loo, pos_label=True, zero_division=0)
recall_loo      = recall_score   (y_true_loo, y_pred_loo, pos_label=True, zero_division=0)
f1_loo          = f1_score       (y_true_loo, y_pred_loo, pos_label=True, zero_division=0)
accuracy_loo    = accuracy_score (y_true_loo, y_pred_loo)
specificity_loo = tn_l / (tn_l + fp_l) if (tn_l + fp_l) > 0 else 0.0

print("\n" + "=" * 60)
print(" LOO 기준 자기참조 검증 결과 (양성 = TRUE 진성 핀테크)")
print("=" * 60)
print(f"\n[혼동행렬 (LOO)]")
print(f"                          예측 FALSE   예측 TRUE")
print(f"  실제 FALSE (안티시드)   {tn_l:>8}     {fp_l:>8}")
print(f"  실제 TRUE  (시드)       {fn_l:>8}     {tp_l:>8}")

print(f"\n[LOO 성능 지표]")
print(f"  Precision   = {precision_loo:.4f}   ({tp_l} / {tp_l+fp_l})")
print(f"  Recall      = {recall_loo:.4f}   ({tp_l} / {tp_l+fn_l})")
print(f"  F1 Score    = {f1_loo:.4f}")
print(f"  Accuracy    = {accuracy_loo:.4f}   ({tp_l+tn_l} / {len(y_true_loo)})")
print(f"  Specificity = {specificity_loo:.4f}   ({tn_l} / {tn_l+fp_l})")

# ── Step 8) 원본 vs LOO 결과 나란히 비교 ──────────────────
print("\n" + "=" * 60)
print(" 원본(자기참조 포함) vs LOO(자기참조 제거) 종합 비교")
print("=" * 60)
print(f"\n{'지표':<14}{'원본':>12}{'LOO':>12}{'변동':>14}")
print("-" * 52)
comparisons = [
    ('Precision',   _results_b1['precision'],   precision_loo),
    ('Recall',      _results_b1['recall'],      recall_loo),
    ('F1 Score',    _results_b1['f1'],          f1_loo),
    ('Accuracy',    _results_b1['accuracy'],    accuracy_loo),
    ('Specificity', _results_b1['specificity'], specificity_loo),
]
for name, orig, loo in comparisons:
    delta = loo - orig
    print(f"{name:<14}{orig:>12.4f}{loo:>12.4f}{delta:>+14.4f}")

# ── Step 9) LOO 결과 변수 보관 (셀 7에서 부록 표 갱신용) ──
_results_b1.update({
    'tp_loo': int(tp_l), 'fp_loo': int(fp_l),
    'fn_loo': int(fn_l), 'tn_loo': int(tn_l),
    'precision_loo': precision_loo,
    'recall_loo':    recall_loo,
    'f1_loo':        f1_loo,
    'accuracy_loo':  accuracy_loo,
    'specificity_loo': specificity_loo,
    'flipped':       int(flipped),
})
print("\n[변수 보관 완료] 다음 셀(셀 7)에서 부록 표를 갱신합니다.")

# ─────────────────────────────────────────────────────────────
# B-1 / 셀 7: 부록 표 갱신 (자기참조 + LOO 결과 병기)
# ─────────────────────────────────────────────────────────────

import pandas as pd
from datetime import datetime

r = _results_b1

# 메타데이터
metadata = [
    {'Category': '메타', 'Metric': '산출 일자', 'Value': datetime.now().strftime('%Y-%m-%d'), 'Detail': ''},
    {'Category': '메타', 'Metric': '모집단 크기', 'Value': '71,663건', 'Detail': 'INPADOC 패밀리 정제 후'},
    {'Category': '메타', 'Metric': '진성 (is_fintech=True)', 'Value': '21,381건', 'Detail': '29.8%'},
    {'Category': '메타', 'Metric': '노이즈 (is_fintech=False)', 'Value': '50,282건', 'Detail': '70.2%'},
    {'Category': '메타', 'Metric': '시드 (fintech=TRUE)', 'Value': '157건', 'Detail': 'final_seed.csv'},
    {'Category': '메타', 'Metric': '안티시드 (fintech=FALSE)', 'Value': '443건', 'Detail': 'final_seed.csv'},
]

# 본문 인용 지표 (분포 분리)
main_metrics = [
    {'Category': '분포 비교 [본문]', 'Metric': '진성 그룹 평균 (net_score)',
     'Value': f"{r['mean_true']:+.6f}",  'Detail': f"n={r['n_true']:,}, SD={r['sd_true']:.6f}"},
    {'Category': '분포 비교 [본문]', 'Metric': '노이즈 그룹 평균 (net_score)',
     'Value': f"{r['mean_false']:+.6f}", 'Detail': f"n={r['n_false']:,}, SD={r['sd_false']:.6f}"},
    {'Category': '분포 비교 [본문]', 'Metric': "Welch's t 통계량",
     'Value': f"{r['t_stat']:.2f}", 'Detail': "p < 0.001"},
    {'Category': '효과 크기 [본문]', 'Metric': "Cohen's d",
     'Value': f"{r['cohens_d']:.4f}",
     'Detail': f"95% CI [{r['ci_lower']:.4f}, {r['ci_upper']:.4f}], 'large' (Cohen 1988)"},
    {'Category': '효과 크기 [본문]', 'Metric': "Hedges' g (소표본 보정)",
     'Value': f"{r['hedges_g']:.4f}", 'Detail': "보정계수 ≈ 1.0 (대표본)"},
]

# 자기참조 검증 - 원본 (부록)
self_ref_orig = [
    {'Category': '자기참조 원본 [부록]', 'Metric': '혼동행렬 (TP/FP/FN/TN)',
     'Value': f"{r['tp']}/{r['fp']}/{r['fn']}/{r['tn']}",
     'Detail': "시드/안티시드 자기 자신 포함 평가"},
    {'Category': '자기참조 원본 [부록]', 'Metric': 'Precision',
     'Value': f"{r['precision']:.4f}", 'Detail': f"{r['tp']}/({r['tp']}+{r['fp']})"},
    {'Category': '자기참조 원본 [부록]', 'Metric': 'Recall',
     'Value': f"{r['recall']:.4f}", 'Detail': f"{r['tp']}/({r['tp']}+{r['fn']})"},
    {'Category': '자기참조 원본 [부록]', 'Metric': 'F1 Score',
     'Value': f"{r['f1']:.4f}", 'Detail': "자기 cos_sim=1.0 Top-3 포함의 결과"},
    {'Category': '자기참조 원본 [부록]', 'Metric': 'Specificity',
     'Value': f"{r['specificity']:.4f}", 'Detail': f"{r['tn']}/({r['tn']}+{r['fp']})"},
]

# 자기참조 검증 - LOO (부록)
self_ref_loo = [
    {'Category': 'LOO 검증 [부록]', 'Metric': '혼동행렬 (TP/FP/FN/TN)',
     'Value': f"{r['tp_loo']}/{r['fp_loo']}/{r['fn_loo']}/{r['tn_loo']}",
     'Detail': f"600건 중 {r['flipped']}건 예측 변동 (14.0%)"},
    {'Category': 'LOO 검증 [부록]', 'Metric': 'Precision',
     'Value': f"{r['precision_loo']:.4f}",
     'Detail': f"vs 원본 {r['precision_loo']-r['precision']:+.4f}"},
    {'Category': 'LOO 검증 [부록]', 'Metric': 'Recall',
     'Value': f"{r['recall_loo']:.4f}",
     'Detail': f"vs 원본 {r['recall_loo']-r['recall']:+.4f}"},
    {'Category': 'LOO 검증 [부록]', 'Metric': 'F1 Score',
     'Value': f"{r['f1_loo']:.4f}",
     'Detail': f"vs 원본 {r['f1_loo']-r['f1']:+.4f}"},
    {'Category': 'LOO 검증 [부록]', 'Metric': 'Specificity',
     'Value': f"{r['specificity_loo']:.4f}",
     'Detail': f"vs 원본 {r['specificity_loo']-r['specificity']:+.4f}"},
]

# 해석 / 한계 메모
notes = [
    {'Category': '해석', 'Metric': '본문 정량 검증의 핵심 증거',
     'Value': "Cohen's d = 1.924 (large 기준의 2.4배)",
     'Detail': '분포 분리는 LOO 영향 미미(시드/안티시드 가중치 1% 미만)'},
    {'Category': '해석', 'Metric': '자기참조 검증의 한계',
     'Value': "원본 F1 - LOO F1 = +0.271",
     'Detail': '자기 cos_sim=1.0이 Top-3에 포함되어 점수 부풀림 발생'},
    {'Category': '해석', 'Metric': 'LOO 결과의 학술적 위치',
     'Value': '분류기의 보수적 하한',
     'Detail': 'LOO는 분류기의 의도된 환경(시드 157개 전체)이 아닌 156/442개 환경에서의 평가'},
]

df_final = pd.DataFrame(metadata + main_metrics + self_ref_orig + self_ref_loo + notes)

# 저장
output_path = os.path.join(BASE_PATH, 'Semantic_Validation_Metrics.csv')
df_final.to_csv(output_path, index=False, encoding='utf-8-sig')

print("=" * 60)
print(" 부록 〈표 A-2〉 저장 완료")
print("=" * 60)
print(f"\n  저장 경로: {output_path}")
print(f"  행 수:    {len(df_final)}")
print(f"\n[전체 미리보기]")
print(df_final.to_string(index=False))

